name: hp_cycling
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - setuptools == 45.3.0
  - pip:
    - numpy
    - pandas
    - scikit-learn
    - matplotlib
    - seaborn
    - jupyter
    - pylint
    - notebook
    - tqdm